background {
    monitor =
    path = /home/ivo/Documents/DSC00386.png  # your wallpaper
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    outer_color = rgb(255, 255, 255)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(255, 255, 255)
    placeholder_text = <i>Password...</i>
    position = 0, -100
    halign = center
    valign = center
}
